apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Release.Name}}-webservice
  namespace: {{ .Values.global.NameSpace }}
  labels:
    app: {{ .Chart.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin 
subjects:
- kind: ServiceAccount
  name: {{.Release.Name}}-webservice
  namespace: {{ .Values.global.NameSpace }}
