{{- if eq .Values.global.scm.type "bitbucket" -}}
apiVersion: extensions/v1
kind: Deployment
metadata:
  namespace: {{ .Values.global.NameSpace }}
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Release.Name }}-bitbucket
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-bitbucket
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
          - name: {{ .Release.Name }}-bitbucket
            mountPath: /var/atlassian/application-data/bitbucket
          ports:
          - containerPort: 7990
            name: http
            protocol: TCP
          - containerPort: 7999
            name: ssh
            protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 6
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
      volumes:
        - name: {{ .Release.Name }}-bitbucket
          persistentVolumeClaim:
            {{- if .Values.persistence.existingClaim }}
            claimName: "{{ .Values.persistence.existingClaim}}"
            {{ else }}
            claimName: "{{ .Release.Name }}-bitbucket-pvc"
            {{- end -}}
{{- end -}}
